service: trigger-lambda-on-sqs-event

custom:  
  vars: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.vars.region}   
  role: arn:aws:iam::${self:custom.vars.accountId}:role/${self:custom.vars.roleName}  
  environment:
    REGION: ${self:custom.vars.region}

functions:
  sqsTrigger:
    handler: handler.sqsTrigger   
    role: arn:aws:iam::${self:custom.vars.accountId}:role/${self:custom.vars.roleName}
    environment:
      SQS_URL:
        Ref: gundeboinaSQS
    events:
      - sqs:
          arn:
            Fn::GetAtt: [gundeboinaSQS, Arn]

resources:
 Resources:
   gundeboinaSQS:    
    Type: AWS::SQS::Queue
    Properties:
      QueueName: gundeboina-sqs-dev
      VisibilityTimeout: 180